### ISSUE TITLE
Response crashes the extension

### ISSUE THREAD

**Issue by tomazk8** [lomonosv/json-rpc-chrome-viewer#8]
My JsonRPC returns an empty array as json ("result": "[]") and the extension crashes. All content goes away and I see only white background.

**Comment by lomonosv** [comment]
@tomazk8 Hey! Thank you for reporting the issue. Could you please share the response of your rpc endpoint request which crashes the extension?

**Comment by tomazk8** [comment]
Hey Vladimir. Thanks for your quick response. This is my answer:
`{
  "jsonrpc": "2.0",
  "id": "04db46b9-1fad-4402-beb2-297ed0dd97e4",
  "result": [],
  "error": null,
  "executionTimeInMiliseconds": 15.0
}`

**Comment by lomonosv** [comment]
@tomazk8 It was issue with converting the response to TS. Fixed in 1.3.14 version. Please, update your extension.

**Comment by tomazk8** [comment]
Thanks a lot for the fix Vladimir.
